#! /bin/sh
polybar &
devilspie &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#6411FF"
bspc config focused_border_color "#C76C65"
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
nitrogen --set-scaled /home/shridhar/Downloads/new.jpg

xinput set-prop 11 309 1
picom &
xscreensaver &
redshift -x
redshift -O 2500
brightnessctl s 1%
$HOME/.config/polybar/launch.sh
